//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("ΡόστερModel", "Παίκτες_θέση_FK", "Θέση", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Rosteras.Θέση), "Παίκτες", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Rosteras.Παίκτες), true)]
[assembly: EdmRelationshipAttribute("ΡόστερModel", "FK__Ομάδες__Τελευταί__08EA5793", "Πρωταθλήματα", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Rosteras.Πρωταθλήματα), "Ομάδες", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Rosteras.Ομάδες), true)]
[assembly: EdmRelationshipAttribute("ΡόστερModel", "FK__Παίκτες__Ηλικία__0DAF0CB0", "Ομάδες", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Rosteras.Ομάδες), "Παίκτες", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Rosteras.Παίκτες), true)]
[assembly: EdmRelationshipAttribute("ΡόστερModel", "FK__Προηγούμεν__Χώρα__182C9B23", "Παίκτες", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Rosteras.Παίκτες), "Προηγούμενες_Ομάδες", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Rosteras.Προηγούμενες_Ομάδες), true)]

#endregion

namespace Rosteras
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RosterEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RosterEntities object using the connection string found in the 'RosterEntities' section of the application configuration file.
        /// </summary>
        public RosterEntities() : base("name=RosterEntities", "RosterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RosterEntities object.
        /// </summary>
        public RosterEntities(string connectionString) : base(connectionString, "RosterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RosterEntities object.
        /// </summary>
        public RosterEntities(EntityConnection connection) : base(connection, "RosterEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Θέση> Θέση
        {
            get
            {
                if ((_Θέση == null))
                {
                    _Θέση = base.CreateObjectSet<Θέση>("Θέση");
                }
                return _Θέση;
            }
        }
        private ObjectSet<Θέση> _Θέση;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ομάδες> Ομάδες
        {
            get
            {
                if ((_Ομάδες == null))
                {
                    _Ομάδες = base.CreateObjectSet<Ομάδες>("Ομάδες");
                }
                return _Ομάδες;
            }
        }
        private ObjectSet<Ομάδες> _Ομάδες;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Παίκτες> Παίκτες
        {
            get
            {
                if ((_Παίκτες == null))
                {
                    _Παίκτες = base.CreateObjectSet<Παίκτες>("Παίκτες");
                }
                return _Παίκτες;
            }
        }
        private ObjectSet<Παίκτες> _Παίκτες;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Προηγούμενες_Ομάδες> Προηγούμενες_Ομάδες
        {
            get
            {
                if ((_Προηγούμενες_Ομάδες == null))
                {
                    _Προηγούμενες_Ομάδες = base.CreateObjectSet<Προηγούμενες_Ομάδες>("Προηγούμενες_Ομάδες");
                }
                return _Προηγούμενες_Ομάδες;
            }
        }
        private ObjectSet<Προηγούμενες_Ομάδες> _Προηγούμενες_Ομάδες;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Πρωταθλήματα> Πρωταθλήματα
        {
            get
            {
                if ((_Πρωταθλήματα == null))
                {
                    _Πρωταθλήματα = base.CreateObjectSet<Πρωταθλήματα>("Πρωταθλήματα");
                }
                return _Πρωταθλήματα;
            }
        }
        private ObjectSet<Πρωταθλήματα> _Πρωταθλήματα;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Θέση EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToΘέση(Θέση θέση)
        {
            base.AddObject("Θέση", θέση);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ομάδες EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToΟμάδες(Ομάδες ομάδες)
        {
            base.AddObject("Ομάδες", ομάδες);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Παίκτες EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToΠαίκτες(Παίκτες παίκτες)
        {
            base.AddObject("Παίκτες", παίκτες);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Προηγούμενες_Ομάδες EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToΠροηγούμενες_Ομάδες(Προηγούμενες_Ομάδες προηγούμενες_Ομάδες)
        {
            base.AddObject("Προηγούμενες_Ομάδες", προηγούμενες_Ομάδες);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Πρωταθλήματα EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToΠρωταθλήματα(Πρωταθλήματα πρωταθλήματα)
        {
            base.AddObject("Πρωταθλήματα", πρωταθλήματα);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ΡόστερModel", Name="Θέση")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Θέση : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Θέση object.
        /// </summary>
        /// <param name="ονομασία">Initial value of the Ονομασία property.</param>
        public static Θέση CreateΘέση(global::System.String ονομασία)
        {
            Θέση θέση = new Θέση();
            θέση.Ονομασία = ονομασία;
            return θέση;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ονομασία
        {
            get
            {
                return _Ονομασία;
            }
            set
            {
                if (_Ονομασία != value)
                {
                    OnΟνομασίαChanging(value);
                    ReportPropertyChanging("Ονομασία");
                    _Ονομασία = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ονομασία");
                    OnΟνομασίαChanged();
                }
            }
        }
        private global::System.String _Ονομασία;
        partial void OnΟνομασίαChanging(global::System.String value);
        partial void OnΟνομασίαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Σειρά
        {
            get
            {
                return _Σειρά;
            }
            set
            {
                OnΣειράChanging(value);
                ReportPropertyChanging("Σειρά");
                _Σειρά = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Σειρά");
                OnΣειράChanged();
            }
        }
        private global::System.String _Σειρά;
        partial void OnΣειράChanging(global::System.String value);
        partial void OnΣειράChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ΡόστερModel", "Παίκτες_θέση_FK", "Παίκτες")]
        public EntityCollection<Παίκτες> Παίκτες
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Παίκτες>("ΡόστερModel.Παίκτες_θέση_FK", "Παίκτες");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Παίκτες>("ΡόστερModel.Παίκτες_θέση_FK", "Παίκτες", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ΡόστερModel", Name="Ομάδες")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ομάδες : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ομάδες object.
        /// </summary>
        /// <param name="ονομασία">Initial value of the Ονομασία property.</param>
        public static Ομάδες CreateΟμάδες(global::System.String ονομασία)
        {
            Ομάδες ομάδες = new Ομάδες();
            ομάδες.Ονομασία = ονομασία;
            return ομάδες;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ονομασία
        {
            get
            {
                return _Ονομασία;
            }
            set
            {
                if (_Ονομασία != value)
                {
                    OnΟνομασίαChanging(value);
                    ReportPropertyChanging("Ονομασία");
                    _Ονομασία = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ονομασία");
                    OnΟνομασίαChanged();
                }
            }
        }
        private global::System.String _Ονομασία;
        partial void OnΟνομασίαChanging(global::System.String value);
        partial void OnΟνομασίαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Πρωτάθλημα
        {
            get
            {
                return _Πρωτάθλημα;
            }
            set
            {
                OnΠρωτάθλημαChanging(value);
                ReportPropertyChanging("Πρωτάθλημα");
                _Πρωτάθλημα = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Πρωτάθλημα");
                OnΠρωτάθλημαChanged();
            }
        }
        private global::System.String _Πρωτάθλημα;
        partial void OnΠρωτάθλημαChanging(global::System.String value);
        partial void OnΠρωτάθλημαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Περιοχή
        {
            get
            {
                return _Περιοχή;
            }
            set
            {
                OnΠεριοχήChanging(value);
                ReportPropertyChanging("Περιοχή");
                _Περιοχή = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Περιοχή");
                OnΠεριοχήChanged();
            }
        }
        private global::System.String _Περιοχή;
        partial void OnΠεριοχήChanging(global::System.String value);
        partial void OnΠεριοχήChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Χρώματα
        {
            get
            {
                return _Χρώματα;
            }
            set
            {
                OnΧρώματαChanging(value);
                ReportPropertyChanging("Χρώματα");
                _Χρώματα = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Χρώματα");
                OnΧρώματαChanged();
            }
        }
        private global::System.String _Χρώματα;
        partial void OnΧρώματαChanging(global::System.String value);
        partial void OnΧρώματαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Έτος_Ίδρυσης
        {
            get
            {
                return _Έτος_Ίδρυσης;
            }
            set
            {
                OnΈτος_ΊδρυσηςChanging(value);
                ReportPropertyChanging("Έτος_Ίδρυσης");
                _Έτος_Ίδρυσης = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Έτος_Ίδρυσης");
                OnΈτος_ΊδρυσηςChanged();
            }
        }
        private global::System.String _Έτος_Ίδρυσης;
        partial void OnΈτος_ΊδρυσηςChanging(global::System.String value);
        partial void OnΈτος_ΊδρυσηςChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Αριθμός_Πρωταθλημάτων
        {
            get
            {
                return _Αριθμός_Πρωταθλημάτων;
            }
            set
            {
                OnΑριθμός_ΠρωταθλημάτωνChanging(value);
                ReportPropertyChanging("Αριθμός_Πρωταθλημάτων");
                _Αριθμός_Πρωταθλημάτων = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Αριθμός_Πρωταθλημάτων");
                OnΑριθμός_ΠρωταθλημάτωνChanged();
            }
        }
        private Nullable<global::System.Int32> _Αριθμός_Πρωταθλημάτων;
        partial void OnΑριθμός_ΠρωταθλημάτωνChanging(Nullable<global::System.Int32> value);
        partial void OnΑριθμός_ΠρωταθλημάτωνChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Αριθμός_Κυπέλλων
        {
            get
            {
                return _Αριθμός_Κυπέλλων;
            }
            set
            {
                OnΑριθμός_ΚυπέλλωνChanging(value);
                ReportPropertyChanging("Αριθμός_Κυπέλλων");
                _Αριθμός_Κυπέλλων = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Αριθμός_Κυπέλλων");
                OnΑριθμός_ΚυπέλλωνChanged();
            }
        }
        private Nullable<global::System.Int32> _Αριθμός_Κυπέλλων;
        partial void OnΑριθμός_ΚυπέλλωνChanging(Nullable<global::System.Int32> value);
        partial void OnΑριθμός_ΚυπέλλωνChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Τελευταίο_Τρόπαιο
        {
            get
            {
                return _Τελευταίο_Τρόπαιο;
            }
            set
            {
                OnΤελευταίο_ΤρόπαιοChanging(value);
                ReportPropertyChanging("Τελευταίο_Τρόπαιο");
                _Τελευταίο_Τρόπαιο = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Τελευταίο_Τρόπαιο");
                OnΤελευταίο_ΤρόπαιοChanged();
            }
        }
        private global::System.String _Τελευταίο_Τρόπαιο;
        partial void OnΤελευταίο_ΤρόπαιοChanging(global::System.String value);
        partial void OnΤελευταίο_ΤρόπαιοChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Έδρα
        {
            get
            {
                return _Έδρα;
            }
            set
            {
                OnΈδραChanging(value);
                ReportPropertyChanging("Έδρα");
                _Έδρα = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Έδρα");
                OnΈδραChanged();
            }
        }
        private global::System.String _Έδρα;
        partial void OnΈδραChanging(global::System.String value);
        partial void OnΈδραChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Προπονητής
        {
            get
            {
                return _Προπονητής;
            }
            set
            {
                OnΠροπονητήςChanging(value);
                ReportPropertyChanging("Προπονητής");
                _Προπονητής = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Προπονητής");
                OnΠροπονητήςChanged();
            }
        }
        private global::System.String _Προπονητής;
        partial void OnΠροπονητήςChanging(global::System.String value);
        partial void OnΠροπονητήςChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Πρόεδρος
        {
            get
            {
                return _Πρόεδρος;
            }
            set
            {
                OnΠρόεδροςChanging(value);
                ReportPropertyChanging("Πρόεδρος");
                _Πρόεδρος = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Πρόεδρος");
                OnΠρόεδροςChanged();
            }
        }
        private global::System.String _Πρόεδρος;
        partial void OnΠρόεδροςChanging(global::System.String value);
        partial void OnΠρόεδροςChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ΡόστερModel", "FK__Ομάδες__Τελευταί__08EA5793", "Πρωταθλήματα")]
        public Πρωταθλήματα Πρωταθλήματα
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Πρωταθλήματα>("ΡόστερModel.FK__Ομάδες__Τελευταί__08EA5793", "Πρωταθλήματα").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Πρωταθλήματα>("ΡόστερModel.FK__Ομάδες__Τελευταί__08EA5793", "Πρωταθλήματα").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Πρωταθλήματα> ΠρωταθλήματαReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Πρωταθλήματα>("ΡόστερModel.FK__Ομάδες__Τελευταί__08EA5793", "Πρωταθλήματα");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Πρωταθλήματα>("ΡόστερModel.FK__Ομάδες__Τελευταί__08EA5793", "Πρωταθλήματα", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ΡόστερModel", "FK__Παίκτες__Ηλικία__0DAF0CB0", "Παίκτες")]
        public EntityCollection<Παίκτες> Παίκτες
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Παίκτες>("ΡόστερModel.FK__Παίκτες__Ηλικία__0DAF0CB0", "Παίκτες");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Παίκτες>("ΡόστερModel.FK__Παίκτες__Ηλικία__0DAF0CB0", "Παίκτες", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ΡόστερModel", Name="Παίκτες")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Παίκτες : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Παίκτες object.
        /// </summary>
        /// <param name="iD_Παίκτη">Initial value of the ID_Παίκτη property.</param>
        public static Παίκτες CreateΠαίκτες(global::System.String iD_Παίκτη)
        {
            Παίκτες παίκτες = new Παίκτες();
            παίκτες.ID_Παίκτη = iD_Παίκτη;
            return παίκτες;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Παίκτη
        {
            get
            {
                return _ID_Παίκτη;
            }
            set
            {
                if (_ID_Παίκτη != value)
                {
                    OnID_ΠαίκτηChanging(value);
                    ReportPropertyChanging("ID_Παίκτη");
                    _ID_Παίκτη = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Παίκτη");
                    OnID_ΠαίκτηChanged();
                }
            }
        }
        private global::System.String _ID_Παίκτη;
        partial void OnID_ΠαίκτηChanging(global::System.String value);
        partial void OnID_ΠαίκτηChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Όνομα
        {
            get
            {
                return _Όνομα;
            }
            set
            {
                OnΌνομαChanging(value);
                ReportPropertyChanging("Όνομα");
                _Όνομα = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Όνομα");
                OnΌνομαChanged();
            }
        }
        private global::System.String _Όνομα;
        partial void OnΌνομαChanging(global::System.String value);
        partial void OnΌνομαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Τρέχουσα_Ομάδα
        {
            get
            {
                return _Τρέχουσα_Ομάδα;
            }
            set
            {
                OnΤρέχουσα_ΟμάδαChanging(value);
                ReportPropertyChanging("Τρέχουσα_Ομάδα");
                _Τρέχουσα_Ομάδα = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Τρέχουσα_Ομάδα");
                OnΤρέχουσα_ΟμάδαChanged();
            }
        }
        private global::System.String _Τρέχουσα_Ομάδα;
        partial void OnΤρέχουσα_ΟμάδαChanging(global::System.String value);
        partial void OnΤρέχουσα_ΟμάδαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Ύψος
        {
            get
            {
                return _Ύψος;
            }
            set
            {
                OnΎψοςChanging(value);
                ReportPropertyChanging("Ύψος");
                _Ύψος = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ύψος");
                OnΎψοςChanged();
            }
        }
        private Nullable<global::System.Double> _Ύψος;
        partial void OnΎψοςChanging(Nullable<global::System.Double> value);
        partial void OnΎψοςChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Γκολ_στη_Superleague
        {
            get
            {
                return _Γκολ_στη_Superleague;
            }
            set
            {
                OnΓκολ_στη_SuperleagueChanging(value);
                ReportPropertyChanging("Γκολ_στη_Superleague");
                _Γκολ_στη_Superleague = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Γκολ_στη_Superleague");
                OnΓκολ_στη_SuperleagueChanged();
            }
        }
        private Nullable<global::System.Int32> _Γκολ_στη_Superleague;
        partial void OnΓκολ_στη_SuperleagueChanging(Nullable<global::System.Int32> value);
        partial void OnΓκολ_στη_SuperleagueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Γκολ_στη_Football_league
        {
            get
            {
                return _Γκολ_στη_Football_league;
            }
            set
            {
                OnΓκολ_στη_Football_leagueChanging(value);
                ReportPropertyChanging("Γκολ_στη_Football_league");
                _Γκολ_στη_Football_league = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Γκολ_στη_Football_league");
                OnΓκολ_στη_Football_leagueChanged();
            }
        }
        private Nullable<global::System.Int32> _Γκολ_στη_Football_league;
        partial void OnΓκολ_στη_Football_leagueChanging(Nullable<global::System.Int32> value);
        partial void OnΓκολ_στη_Football_leagueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Ηλικία
        {
            get
            {
                return _Ηλικία;
            }
            set
            {
                OnΗλικίαChanging(value);
                ReportPropertyChanging("Ηλικία");
                _Ηλικία = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ηλικία");
                OnΗλικίαChanged();
            }
        }
        private Nullable<global::System.Int32> _Ηλικία;
        partial void OnΗλικίαChanging(Nullable<global::System.Int32> value);
        partial void OnΗλικίαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Θέση
        {
            get
            {
                return _Θέση;
            }
            set
            {
                OnΘέσηChanging(value);
                ReportPropertyChanging("Θέση");
                _Θέση = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Θέση");
                OnΘέσηChanged();
            }
        }
        private global::System.String _Θέση;
        partial void OnΘέσηChanging(global::System.String value);
        partial void OnΘέσηChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Χώρα
        {
            get
            {
                return _Χώρα;
            }
            set
            {
                OnΧώραChanging(value);
                ReportPropertyChanging("Χώρα");
                _Χώρα = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Χώρα");
                OnΧώραChanged();
            }
        }
        private global::System.String _Χώρα;
        partial void OnΧώραChanging(global::System.String value);
        partial void OnΧώραChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Εμφανίσεις_στη_Superleague
        {
            get
            {
                return _Εμφανίσεις_στη_Superleague;
            }
            set
            {
                OnΕμφανίσεις_στη_SuperleagueChanging(value);
                ReportPropertyChanging("Εμφανίσεις_στη_Superleague");
                _Εμφανίσεις_στη_Superleague = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Εμφανίσεις_στη_Superleague");
                OnΕμφανίσεις_στη_SuperleagueChanged();
            }
        }
        private Nullable<global::System.Int32> _Εμφανίσεις_στη_Superleague;
        partial void OnΕμφανίσεις_στη_SuperleagueChanging(Nullable<global::System.Int32> value);
        partial void OnΕμφανίσεις_στη_SuperleagueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Εμφανίσεις_στη_Football_league
        {
            get
            {
                return _Εμφανίσεις_στη_Football_league;
            }
            set
            {
                OnΕμφανίσεις_στη_Football_leagueChanging(value);
                ReportPropertyChanging("Εμφανίσεις_στη_Football_league");
                _Εμφανίσεις_στη_Football_league = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Εμφανίσεις_στη_Football_league");
                OnΕμφανίσεις_στη_Football_leagueChanged();
            }
        }
        private Nullable<global::System.Int32> _Εμφανίσεις_στη_Football_league;
        partial void OnΕμφανίσεις_στη_Football_leagueChanging(Nullable<global::System.Int32> value);
        partial void OnΕμφανίσεις_στη_Football_leagueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Δανεικός_από
        {
            get
            {
                return _Δανεικός_από;
            }
            set
            {
                OnΔανεικός_απόChanging(value);
                ReportPropertyChanging("Δανεικός_από");
                _Δανεικός_από = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Δανεικός_από");
                OnΔανεικός_απόChanged();
            }
        }
        private global::System.String _Δανεικός_από;
        partial void OnΔανεικός_απόChanging(global::System.String value);
        partial void OnΔανεικός_απόChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Φετινές_Συμμετοχές_στη_Superleague
        {
            get
            {
                return _Φετινές_Συμμετοχές_στη_Superleague;
            }
            set
            {
                OnΦετινές_Συμμετοχές_στη_SuperleagueChanging(value);
                ReportPropertyChanging("Φετινές_Συμμετοχές_στη_Superleague");
                _Φετινές_Συμμετοχές_στη_Superleague = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Φετινές_Συμμετοχές_στη_Superleague");
                OnΦετινές_Συμμετοχές_στη_SuperleagueChanged();
            }
        }
        private Nullable<global::System.Int32> _Φετινές_Συμμετοχές_στη_Superleague;
        partial void OnΦετινές_Συμμετοχές_στη_SuperleagueChanging(Nullable<global::System.Int32> value);
        partial void OnΦετινές_Συμμετοχές_στη_SuperleagueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Φετινές_Συμμετοχές_στη_Football_league
        {
            get
            {
                return _Φετινές_Συμμετοχές_στη_Football_league;
            }
            set
            {
                OnΦετινές_Συμμετοχές_στη_Football_leagueChanging(value);
                ReportPropertyChanging("Φετινές_Συμμετοχές_στη_Football_league");
                _Φετινές_Συμμετοχές_στη_Football_league = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Φετινές_Συμμετοχές_στη_Football_league");
                OnΦετινές_Συμμετοχές_στη_Football_leagueChanged();
            }
        }
        private Nullable<global::System.Int32> _Φετινές_Συμμετοχές_στη_Football_league;
        partial void OnΦετινές_Συμμετοχές_στη_Football_leagueChanging(Nullable<global::System.Int32> value);
        partial void OnΦετινές_Συμμετοχές_στη_Football_leagueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Φετινά_Γκολ_στη_Superleague
        {
            get
            {
                return _Φετινά_Γκολ_στη_Superleague;
            }
            set
            {
                OnΦετινά_Γκολ_στη_SuperleagueChanging(value);
                ReportPropertyChanging("Φετινά_Γκολ_στη_Superleague");
                _Φετινά_Γκολ_στη_Superleague = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Φετινά_Γκολ_στη_Superleague");
                OnΦετινά_Γκολ_στη_SuperleagueChanged();
            }
        }
        private Nullable<global::System.Int32> _Φετινά_Γκολ_στη_Superleague;
        partial void OnΦετινά_Γκολ_στη_SuperleagueChanging(Nullable<global::System.Int32> value);
        partial void OnΦετινά_Γκολ_στη_SuperleagueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Φετινά_Γκολ_στη_Football_league
        {
            get
            {
                return _Φετινά_Γκολ_στη_Football_league;
            }
            set
            {
                OnΦετινά_Γκολ_στη_Football_leagueChanging(value);
                ReportPropertyChanging("Φετινά_Γκολ_στη_Football_league");
                _Φετινά_Γκολ_στη_Football_league = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Φετινά_Γκολ_στη_Football_league");
                OnΦετινά_Γκολ_στη_Football_leagueChanged();
            }
        }
        private Nullable<global::System.Int32> _Φετινά_Γκολ_στη_Football_league;
        partial void OnΦετινά_Γκολ_στη_Football_leagueChanging(Nullable<global::System.Int32> value);
        partial void OnΦετινά_Γκολ_στη_Football_leagueChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ΡόστερModel", "Παίκτες_θέση_FK", "Θέση")]
        public Θέση Θέση1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Θέση>("ΡόστερModel.Παίκτες_θέση_FK", "Θέση").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Θέση>("ΡόστερModel.Παίκτες_θέση_FK", "Θέση").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Θέση> Θέση1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Θέση>("ΡόστερModel.Παίκτες_θέση_FK", "Θέση");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Θέση>("ΡόστερModel.Παίκτες_θέση_FK", "Θέση", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ΡόστερModel", "FK__Παίκτες__Ηλικία__0DAF0CB0", "Ομάδες")]
        public Ομάδες Ομάδες
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ομάδες>("ΡόστερModel.FK__Παίκτες__Ηλικία__0DAF0CB0", "Ομάδες").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ομάδες>("ΡόστερModel.FK__Παίκτες__Ηλικία__0DAF0CB0", "Ομάδες").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Ομάδες> ΟμάδεςReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Ομάδες>("ΡόστερModel.FK__Παίκτες__Ηλικία__0DAF0CB0", "Ομάδες");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Ομάδες>("ΡόστερModel.FK__Παίκτες__Ηλικία__0DAF0CB0", "Ομάδες", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ΡόστερModel", "FK__Προηγούμεν__Χώρα__182C9B23", "Προηγούμενες_Ομάδες")]
        public EntityCollection<Προηγούμενες_Ομάδες> Προηγούμενες_Ομάδες
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Προηγούμενες_Ομάδες>("ΡόστερModel.FK__Προηγούμεν__Χώρα__182C9B23", "Προηγούμενες_Ομάδες");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Προηγούμενες_Ομάδες>("ΡόστερModel.FK__Προηγούμεν__Χώρα__182C9B23", "Προηγούμενες_Ομάδες", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ΡόστερModel", Name="Προηγούμενες_Ομάδες")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Προηγούμενες_Ομάδες : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Προηγούμενες_Ομάδες object.
        /// </summary>
        /// <param name="iD_Παίκτη">Initial value of the ID_Παίκτη property.</param>
        /// <param name="ομάδα">Initial value of the Ομάδα property.</param>
        public static Προηγούμενες_Ομάδες CreateΠροηγούμενες_Ομάδες(global::System.String iD_Παίκτη, global::System.String ομάδα)
        {
            Προηγούμενες_Ομάδες προηγούμενες_Ομάδες = new Προηγούμενες_Ομάδες();
            προηγούμενες_Ομάδες.ID_Παίκτη = iD_Παίκτη;
            προηγούμενες_Ομάδες.Ομάδα = ομάδα;
            return προηγούμενες_Ομάδες;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID_Παίκτη
        {
            get
            {
                return _ID_Παίκτη;
            }
            set
            {
                if (_ID_Παίκτη != value)
                {
                    OnID_ΠαίκτηChanging(value);
                    ReportPropertyChanging("ID_Παίκτη");
                    _ID_Παίκτη = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID_Παίκτη");
                    OnID_ΠαίκτηChanged();
                }
            }
        }
        private global::System.String _ID_Παίκτη;
        partial void OnID_ΠαίκτηChanging(global::System.String value);
        partial void OnID_ΠαίκτηChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ομάδα
        {
            get
            {
                return _Ομάδα;
            }
            set
            {
                if (_Ομάδα != value)
                {
                    OnΟμάδαChanging(value);
                    ReportPropertyChanging("Ομάδα");
                    _Ομάδα = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ομάδα");
                    OnΟμάδαChanged();
                }
            }
        }
        private global::System.String _Ομάδα;
        partial void OnΟμάδαChanging(global::System.String value);
        partial void OnΟμάδαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Χώρα
        {
            get
            {
                return _Χώρα;
            }
            set
            {
                OnΧώραChanging(value);
                ReportPropertyChanging("Χώρα");
                _Χώρα = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Χώρα");
                OnΧώραChanged();
            }
        }
        private global::System.String _Χώρα;
        partial void OnΧώραChanging(global::System.String value);
        partial void OnΧώραChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ΡόστερModel", "FK__Προηγούμεν__Χώρα__182C9B23", "Παίκτες")]
        public Παίκτες Παίκτες
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Παίκτες>("ΡόστερModel.FK__Προηγούμεν__Χώρα__182C9B23", "Παίκτες").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Παίκτες>("ΡόστερModel.FK__Προηγούμεν__Χώρα__182C9B23", "Παίκτες").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Παίκτες> ΠαίκτεςReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Παίκτες>("ΡόστερModel.FK__Προηγούμεν__Χώρα__182C9B23", "Παίκτες");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Παίκτες>("ΡόστερModel.FK__Προηγούμεν__Χώρα__182C9B23", "Παίκτες", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ΡόστερModel", Name="Πρωταθλήματα")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Πρωταθλήματα : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Πρωταθλήματα object.
        /// </summary>
        /// <param name="ονομασία">Initial value of the Ονομασία property.</param>
        public static Πρωταθλήματα CreateΠρωταθλήματα(global::System.String ονομασία)
        {
            Πρωταθλήματα πρωταθλήματα = new Πρωταθλήματα();
            πρωταθλήματα.Ονομασία = ονομασία;
            return πρωταθλήματα;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Ονομασία
        {
            get
            {
                return _Ονομασία;
            }
            set
            {
                if (_Ονομασία != value)
                {
                    OnΟνομασίαChanging(value);
                    ReportPropertyChanging("Ονομασία");
                    _Ονομασία = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Ονομασία");
                    OnΟνομασίαChanged();
                }
            }
        }
        private global::System.String _Ονομασία;
        partial void OnΟνομασίαChanging(global::System.String value);
        partial void OnΟνομασίαChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Τάξη
        {
            get
            {
                return _Τάξη;
            }
            set
            {
                OnΤάξηChanging(value);
                ReportPropertyChanging("Τάξη");
                _Τάξη = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Τάξη");
                OnΤάξηChanged();
            }
        }
        private global::System.String _Τάξη;
        partial void OnΤάξηChanging(global::System.String value);
        partial void OnΤάξηChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Τελευταίος_Πρωταθλήτης
        {
            get
            {
                return _Τελευταίος_Πρωταθλήτης;
            }
            set
            {
                OnΤελευταίος_ΠρωταθλήτηςChanging(value);
                ReportPropertyChanging("Τελευταίος_Πρωταθλήτης");
                _Τελευταίος_Πρωταθλήτης = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Τελευταίος_Πρωταθλήτης");
                OnΤελευταίος_ΠρωταθλήτηςChanged();
            }
        }
        private global::System.String _Τελευταίος_Πρωταθλήτης;
        partial void OnΤελευταίος_ΠρωταθλήτηςChanging(global::System.String value);
        partial void OnΤελευταίος_ΠρωταθλήτηςChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ΡόστερModel", "FK__Ομάδες__Τελευταί__08EA5793", "Ομάδες")]
        public EntityCollection<Ομάδες> Ομάδες
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Ομάδες>("ΡόστερModel.FK__Ομάδες__Τελευταί__08EA5793", "Ομάδες");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Ομάδες>("ΡόστερModel.FK__Ομάδες__Τελευταί__08EA5793", "Ομάδες", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
